# Generated by Django 2.0.5 on 2018-09-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_score', models.IntegerField()),
                ('underdog_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(choices=[('FAV_TEAM', 'Favorite'), ('UNDER_TEAM', 'Underdog')], default='FAV_TEAM', max_length=15)),
                ('spread', models.FloatField()),
                ('overUnder', models.FloatField()),
                ('week', models.IntegerField()),
                ('game_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(choices=[('FAV_TEAM', 'Favorite'), ('UNDER_TEAM', 'Underdog')], default='FAV_TEAM', max_length=15)),
                ('overUnder', models.CharField(choices=[('OVER', 'Over'), ('UNDER', 'Under')], default='OVER', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matchup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdbPool.Matchup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matchup',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav', to='zdbPool.NFLTeam'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='underdog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='under', to='zdbPool.NFLTeam'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='matchup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zdbPool.Matchup'),
        ),
    ]
